#include "Arduino.h"

#define MELODY1 { \
VIERTEL, b3, NORMAL, \
HALBE, a3, NORMAL, \
ACHTEL, h3, NORMAL, \
ACHTEL, h3, NORMAL \
}

#define MELODY2 { \
VIERTEL, b1, NORMAL, \
VIERTEL, a1, NORMAL, \
VIERTEL, a1, NORMAL, \
VIERTEL, a1, NORMAL \
}
